// Code generated by mockery v2.2.1. DO NOT EDIT.

package db

import (
	db_models "hydro_monitor/web_api/pkg/models/db_models"

	mock "github.com/stretchr/testify/mock"

	table "github.com/scylladb/gocqlx/v2/table"
)

// ClientMock is an autogenerated mock type for the Client type
type ClientMock struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *ClientMock) Close() {
	_m.Called()
}

// CreateKeyspace provides a mock function with given fields: keyspaceName, replicationFactor
func (_m *ClientMock) CreateKeyspace(keyspaceName string, replicationFactor int) error {
	ret := _m.Called(keyspaceName, replicationFactor)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(keyspaceName, replicationFactor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0, args
func (_m *ClientMock) Delete(_a0 *table.Table, args db_models.DbDTO) error {
	ret := _m.Called(_a0, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(*table.Table, db_models.DbDTO) error); ok {
		r0 = rf(_a0, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: _a0, args
func (_m *ClientMock) Get(_a0 *table.Table, args db_models.DbDTO) error {
	ret := _m.Called(_a0, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(*table.Table, db_models.DbDTO) error); ok {
		r0 = rf(_a0, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: _a0, args
func (_m *ClientMock) Insert(_a0 *table.Table, args db_models.DbDTO) error {
	ret := _m.Called(_a0, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(*table.Table, db_models.DbDTO) error); ok {
		r0 = rf(_a0, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Migrate provides a mock function with given fields: dir
func (_m *ClientMock) Migrate(dir string) {
	_m.Called(dir)
}

// SafeInsert provides a mock function with given fields: _a0, args
func (_m *ClientMock) SafeInsert(_a0 *table.Table, args db_models.DbDTO) (bool, error) {
	ret := _m.Called(_a0, args)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*table.Table, db_models.DbDTO) bool); ok {
		r0 = rf(_a0, args)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*table.Table, db_models.DbDTO) error); ok {
		r1 = rf(_a0, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SafeUpdate provides a mock function with given fields: _a0, args
func (_m *ClientMock) SafeUpdate(_a0 *table.Table, args db_models.DbDTO) (bool, error) {
	ret := _m.Called(_a0, args)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*table.Table, db_models.DbDTO) bool); ok {
		r0 = rf(_a0, args)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*table.Table, db_models.DbDTO) error); ok {
		r1 = rf(_a0, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Select provides a mock function with given fields: _a0, args, pageState, pageSize
func (_m *ClientMock) Select(_a0 *table.Table, args db_models.SelectDTO, pageState []byte, pageSize int) ([]byte, error) {
	ret := _m.Called(_a0, args, pageState, pageSize)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(*table.Table, db_models.SelectDTO, []byte, int) []byte); ok {
		r0 = rf(_a0, args, pageState, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*table.Table, db_models.SelectDTO, []byte, int) error); ok {
		r1 = rf(_a0, args, pageState, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectAll provides a mock function with given fields: _a0, args
func (_m *ClientMock) SelectAll(_a0 *table.Table, args db_models.SelectDTO) error {
	ret := _m.Called(_a0, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(*table.Table, db_models.SelectDTO) error); ok {
		r0 = rf(_a0, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0, args
func (_m *ClientMock) Update(_a0 *table.Table, args db_models.DbDTO) error {
	ret := _m.Called(_a0, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(*table.Table, db_models.DbDTO) error); ok {
		r0 = rf(_a0, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
