// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	table "github.com/scylladb/gocqlx/table"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Client) Close() {
	_m.Called()
}

// Get provides a mock function with given fields: _a0, args
func (_m *Client) Get(_a0 *table.Table, args interface{}) error {
	ret := _m.Called(_a0, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(*table.Table, interface{}) error); ok {
		r0 = rf(_a0, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: _a0, args
func (_m *Client) Insert(_a0 *table.Table, args interface{}) error {
	ret := _m.Called(_a0, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(*table.Table, interface{}) error); ok {
		r0 = rf(_a0, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Migrate provides a mock function with given fields: dir
func (_m *Client) Migrate(dir string) {
	_m.Called(dir)
}
