// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	table "github.com/scylladb/gocqlx/table"
	mock "github.com/stretchr/testify/mock"
)

// DbClient is an autogenerated mock type for the DbClient type
type DbClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *DbClient) Close() {
	_m.Called()
}

// Get provides a mock function with given fields: _a0, args
func (_m *DbClient) Get(_a0 *table.Table, args interface{}) error {
	ret := _m.Called(_a0, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(*table.Table, interface{}) error); ok {
		r0 = rf(_a0, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
