// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ReadingsController is an autogenerated mock type for the ReadingsController type
type ReadingsController struct {
	mock.Mock
}

// AddPhotoToReading provides a mock function with given fields: c
func (_m *ReadingsController) AddPhotoToReading(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateReading provides a mock function with given fields: c
func (_m *ReadingsController) CreateReading(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNodeReading provides a mock function with given fields: c
func (_m *ReadingsController) GetNodeReading(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNodeReadings provides a mock function with given fields: c
func (_m *ReadingsController) GetNodeReadings(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetReadingPhoto provides a mock function with given fields: c
func (_m *ReadingsController) GetReadingPhoto(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
