// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	qb "github.com/scylladb/gocqlx/qb"
	mock "github.com/stretchr/testify/mock"
)

// SelectDTO is an autogenerated mock type for the SelectDTO type
type SelectDTO struct {
	mock.Mock
}

// GetArgs provides a mock function with given fields:
func (_m *SelectDTO) GetArgs() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// GetBindMap provides a mock function with given fields:
func (_m *SelectDTO) GetBindMap() qb.M {
	ret := _m.Called()

	var r0 qb.M
	if rf, ok := ret.Get(0).(func() qb.M); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(qb.M)
		}
	}

	return r0
}

// GetColumns provides a mock function with given fields:
func (_m *SelectDTO) GetColumns() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
