// Code generated by mockery v2.2.1. DO NOT EDIT.

package services

import (
	api_models "hydro_monitor/web_api/pkg/models/api_models"

	mock "github.com/stretchr/testify/mock"
)

// NodeServiceMock is an autogenerated mock type for the NodeService type
type NodeServiceMock struct {
	mock.Mock
}

// CreateNode provides a mock function with given fields: node
func (_m *NodeServiceMock) CreateNode(node *api_models.NodeDTO) (*api_models.NodeDTO, ServiceError) {
	ret := _m.Called(node)

	var r0 *api_models.NodeDTO
	if rf, ok := ret.Get(0).(func(*api_models.NodeDTO) *api_models.NodeDTO); ok {
		r0 = rf(node)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api_models.NodeDTO)
		}
	}

	var r1 ServiceError
	if rf, ok := ret.Get(1).(func(*api_models.NodeDTO) ServiceError); ok {
		r1 = rf(node)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(ServiceError)
		}
	}

	return r0, r1
}

// CreateNodeConfiguration provides a mock function with given fields: nodeId, configuration
func (_m *NodeServiceMock) CreateNodeConfiguration(nodeId string, configuration map[string]*api_models.StateDTO) error {
	ret := _m.Called(nodeId, configuration)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]*api_models.StateDTO) error); ok {
		r0 = rf(nodeId, configuration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteNode provides a mock function with given fields: nodeId
func (_m *NodeServiceMock) DeleteNode(nodeId string) error {
	ret := _m.Called(nodeId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(nodeId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNode provides a mock function with given fields: nodeId
func (_m *NodeServiceMock) GetNode(nodeId string) (*api_models.NodeDTO, ServiceError) {
	ret := _m.Called(nodeId)

	var r0 *api_models.NodeDTO
	if rf, ok := ret.Get(0).(func(string) *api_models.NodeDTO); ok {
		r0 = rf(nodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api_models.NodeDTO)
		}
	}

	var r1 ServiceError
	if rf, ok := ret.Get(1).(func(string) ServiceError); ok {
		r1 = rf(nodeId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(ServiceError)
		}
	}

	return r0, r1
}

// GetNodeConfiguration provides a mock function with given fields: nodeId
func (_m *NodeServiceMock) GetNodeConfiguration(nodeId string) (map[string]*api_models.StateDTO, ServiceError) {
	ret := _m.Called(nodeId)

	var r0 map[string]*api_models.StateDTO
	if rf, ok := ret.Get(0).(func(string) map[string]*api_models.StateDTO); ok {
		r0 = rf(nodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*api_models.StateDTO)
		}
	}

	var r1 ServiceError
	if rf, ok := ret.Get(1).(func(string) ServiceError); ok {
		r1 = rf(nodeId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(ServiceError)
		}
	}

	return r0, r1
}

// GetNodeManualReadingStatus provides a mock function with given fields: nodeId
func (_m *NodeServiceMock) GetNodeManualReadingStatus(nodeId string) (*api_models.ManualReadingDTO, error) {
	ret := _m.Called(nodeId)

	var r0 *api_models.ManualReadingDTO
	if rf, ok := ret.Get(0).(func(string) *api_models.ManualReadingDTO); ok {
		r0 = rf(nodeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api_models.ManualReadingDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nodeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNodes provides a mock function with given fields:
func (_m *NodeServiceMock) GetNodes() ([]*api_models.NodeDTO, error) {
	ret := _m.Called()

	var r0 []*api_models.NodeDTO
	if rf, ok := ret.Get(0).(func() []*api_models.NodeDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api_models.NodeDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNode provides a mock function with given fields: node
func (_m *NodeServiceMock) UpdateNode(node *api_models.NodeDTO) ServiceError {
	ret := _m.Called(node)

	var r0 ServiceError
	if rf, ok := ret.Get(0).(func(*api_models.NodeDTO) ServiceError); ok {
		r0 = rf(node)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ServiceError)
		}
	}

	return r0
}

// UpdateNodeManualReading provides a mock function with given fields: nodeId, manualReading
func (_m *NodeServiceMock) UpdateNodeManualReading(nodeId string, manualReading bool) (*api_models.ManualReadingDTO, error) {
	ret := _m.Called(nodeId, manualReading)

	var r0 *api_models.ManualReadingDTO
	if rf, ok := ret.Get(0).(func(string, bool) *api_models.ManualReadingDTO); ok {
		r0 = rf(nodeId, manualReading)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api_models.ManualReadingDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(nodeId, manualReading)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
