basePath: /api
definitions:
  api_models.GetReadingDTO:
    properties:
      manualReading:
        example: false
        type: boolean
      readingId:
        example: 00336270-8191-11ea-a43d-0242ac120003
        type: string
      readingTime:
        example: "2020-04-26T19:47:53.391Z"
        type: string
      waterLevel:
        example: 60
        type: number
    type: object
  api_models.ManualReadingDTO:
    properties:
      manualReading:
        example: false
        type: boolean
    type: object
  api_models.NodeDTO:
    properties:
      description:
        example: Nodo instalado debajo de un puente
        type: string
      id:
        example: lujan-1
        type: string
      manual_reading:
        example: false
        type: boolean
    type: object
  api_models.ReadingDTO:
    properties:
      time:
        example: "2020-04-26T19:47:53.391Z"
        type: string
      waterLevel:
        example: 60
        type: number
    type: object
  api_models.StateDTO:
    properties:
      interval:
        example: 25
        type: integer
      lowerLimit:
        example: 0.5
        type: number
      next:
        example: Alto
        type: string
      picturesNum:
        example: 1
        type: integer
      prev:
        example: Bajo
        type: string
      upperLimit:
        example: 1
        type: number
    type: object
  echo.HTTPError:
    properties:
      code:
        type: integer
      internal:
        description: Stores the error returned by an external dependency
        type: error
      message:
        type: object
    type: object
host: localhost
info:
  contact:
    email: manu.porto94@gmail.com
    name: Manuel Porto
  description: This is the Hydro Monitor Web API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Hydro Monitor Web API
  version: "1.0"
paths:
  /nodes:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api_models.NodeDTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Obtiene todos los nodos
      tags:
      - nodes
    post:
      consumes:
      - application/json
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api_models.NodeDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Crea un nodo
      tags:
      - nodes
  /nodes/{node_id}:
    delete:
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      responses:
        "204": {}
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Borra un nodo
      tags:
      - nodes
    get:
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_models.NodeDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Obtiene la información completa de un nodo
      tags:
      - nodes
  /nodes/{node_id}/configuration:
    get:
      description: Devuelve un mapa de estados (no un array como se ve a continuación)
        en donde la clave de cada uno es el nombre del mismo.
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api_models.StateDTO'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Obtiene la configuración de un nodo
      tags:
      - nodes
    post:
      consumes:
      - application/json
      description: Devuelve un mapa de estados (no un array como se ve a continuación)
        en donde la clave de cada uno es el nombre del mismo.
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api_models.StateDTO'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Crea o actualiza la configuración para el nodo dado.
      tags:
      - nodes
  /nodes/{node_id}/manual-reading:
    get:
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_models.ManualReadingDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Obtiene el estado de medición manual de un nodo
      tags:
      - nodes
    put:
      consumes:
      - application/json
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_models.ManualReadingDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Actualiza el estado de medición manual de un nodo
      tags:
      - nodes
  /nodes/{node_id}/readings:
    get:
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api_models.GetReadingDTO'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Obtiene las mediciones de un nodo
      tags:
      - readings
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      - description: Datos de la medición
        in: body
        name: reading
        required: true
        schema:
          $ref: '#/definitions/api_models.ReadingDTO'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_models.GetReadingDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Crea una medición
      tags:
      - readings
  /nodes/{node_id}/readings/{reading_id}/photos:
    get:
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      - description: ID de la medición
        in: path
        name: reading_id
        required: true
        type: string
      produces:
      - image/jpeg
      responses:
        "200": {}
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Obtiene la foto de una medición
      tags:
      - readings
    post:
      consumes:
      - image/jpeg
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      - description: ID de la medición
        in: path
        name: reading_id
        required: true
        type: string
      - description: Foto de la medición
        in: body
        name: picture
        required: true
        schema:
          $ref: '#/definitions/png'
          type: object
      responses:
        "201": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Agrega una foto a la medición
      tags:
      - readings
  /nodes/{node_id}/readings/{reading_id}s:
    get:
      parameters:
      - description: ID del nodo
        in: path
        name: node_id
        required: true
        type: string
      - description: ID de la medición
        in: path
        name: reading_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_models.GetReadingDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Obtiene los datos de una medición
      tags:
      - readings
swagger: "2.0"
